# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brian Kaufman's Website
email: bkaufman729@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi and welcome to my site. This website hosts projects I have
  worked on or am working on. In addition, I might also throw up
  some blog posts here or there, we'll see.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://briankaufman.me" # the base hostname & protocol for your site
twitter_username: bkaufman729
github_username:  bkaufman729

# Build settings
markdown: kramdown
